{
 "title": "RP Leaderboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketpool_node_score_hist_eth_count",
     "legendFormat": "Active"
    },
    { "expr": "rocketpool_node_total_count", "legendFormat": "Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocketpool_network_balance_eth{unit=\"TotalETH\"}",
     "legendFormat": "ETH -0D"
    },
    {
     "expr": "rocketpool_network_balance_eth{unit=\"TotalRETH\"}",
     "legendFormat": "RETH -0D"
    },
    {
     "expr": "rocketpool_network_balance_eth{unit=\"TotalETH\"} offset 6d",
     "legendFormat": "ETH -6D"
    },
    {
     "expr": "rocketpool_network_balance_eth{unit=\"TotalRETH\"} offset 6d",
     "legendFormat": "RETH -6D"
    }
   ]
  },
  {
   "title": "Minipools",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketpool_minipool_count", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Minipools",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rocketpool_node_minipool_count)"
    }
   ]
  },
  {
   "title": "Minipool Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketpool_minipool_queue_count",
     "legendFormat": "{{depositType}}"
    }
   ]
  },
  { "title": "Staking Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network Fee",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "rocketpool_network_fee_rate", "legendFormat": "{{range}}" }
   ]
  },
  {
   "title": "Network Fee",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocketpool_network_fee_rate{range=\"current\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "ETH/RETH",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocketpool_network_balance_eth{unit=\"TotalETH\"} / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"}"
    }
   ]
  },
  {
   "title": "ETH 2 Head",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "slotclock_present_epoch", "legendFormat": "Epoch" },
    { "expr": "slotclock_present_slot", "legendFormat": "Slot" }
   ]
  },
  {
   "title": "Staking Pool Balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketpool_network_balance_eth", "legendFormat": "{{unit}}" }
   ]
  },
  {
   "title": "Earning for last 24 hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rocketpool_network_balance_eth{unit=\"TotalETH\"} / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"}) / (rocketpool_network_balance_eth{unit=\"TotalETH\"} offset 1d / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"} offset 1d) -1"
    }
   ]
  },
  {
   "title": "Earning from last 7 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rocketpool_network_balance_eth{unit=\"TotalETH\"} / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"}) / (rocketpool_network_balance_eth{unit=\"TotalETH\"} offset 7d / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"} offset 7d) -1"
    }
   ]
  },
  {
   "title": "Earning from last 30 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rocketpool_network_balance_eth{unit=\"TotalETH\"} / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"}) / (rocketpool_network_balance_eth{unit=\"TotalETH\"} offset 30d / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"} offset 30d) -1"
    }
   ]
  },
  {
   "title": "Blocks since balance update",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chain_head_block - ignoring(job, instance) rocketpool_network_updated_block"
    },
    {}
   ]
  },
  {
   "title": "Pool Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocketpool_network_balance_eth{unit=\"StakingETH\"} / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalETH\"}"
    },
    {}
   ]
  },
  {
   "title": "ETH/RETH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketpool_network_balance_eth{unit=\"TotalETH\"} / ignoring(unit) rocketpool_network_balance_eth{unit=\"TotalRETH\"}"
    }
   ]
  },
  {
   "title": "Blocks since balance update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_block - ignoring(job, instance) rocketpool_network_updated_block"
    },
    {}
   ]
  },
  { "title": "Leaderboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Score Evolution",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 48 },
   "targets": [
    { "expr": "rocketpool_node_score_hist_eth", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Score Distribution",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rocketpool_node_score_hist_eth", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "table",
   "gridPos": { "h": 28, "w": 13, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rocketpool_node_score_eth" },
    { "expr": "rocketpool_node_minipool_count" }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketpool_minipool_balance_eth"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rocketpool_minipool_balance_eth[7d]))"
    }
   ]
  }
 ]
}