smartnode:
  image: local/rocketpool:latest
chains:
  eth1:
    client:
      selected: geth
      params:
      - env: ETHSTATS_LABEL
        value: ""
      - env: ETHSTATS_LOGIN
        value: ""
      - env: INFURA_PROJECT_ID
        value: ""
  eth2:
    client:
      selected: lighthouse
      params:
      - env: CUSTOM_GRAFFITI
        value: ""
